blog_name: 法律尽职调查导航
slogan: Legal DD
keywords: 法律, 尽职调查, 法律尽职调查, 尽职调查导航,Due Diligence, Legal
url: https://dd.legal

# Set favicon
#favicon: http://7xqpr6.com1.z0.glb.clouddn.com/blog/2017-04-22-fav.png

# For seo

baidu_analytics: f782b24ccc4ba514130d49aa66892e80
